spring:
  profiles:
    active: dev
  cloud:
    gateway:
#      routes:
#        - id: remoteaddr_route
#          uri: http://example.org
#          predicates:
#            - RemoteAddr=127.0.0.1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeader: "*"
            exposedHeader: "Authorization"
